enum BookCategory {
  ART = 'ART',
  AUTOBIOGRAPHY = 'AUTOBIOGRAPHY',
  NOT_DEFINE = 'NOT_DEFINE',
  BIOGRAPHY = 'BIOGRAPHY',
  BUSINESS = 'BUSINESS',
  COMIC = 'COMIC',
  COMPUTER = 'COMPUTER',
  COOKING = 'COOKING',
  EDUCATION = 'EDUCATION',
  HISTORY = 'HISTORY',
  HORROR = 'HORROR',
}

export default BookCategory
